apiVersion: v1
kind: Service
metadata:
  name: aiops-project-service
  labels:
    app: aiops
spec:
  selector:
    app: aiops
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000