apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kafka

resources:
  - consumer_deployment.yml
  - consumer_service.yml
  - consumer_hpa.yml
  - producer_deployment.yml
  - producer_service.yml
  - producer_hpa.yml